spring:
  datasource:
    url: jdbc:h2:mem:inditexdb
    driverClassName: org.h2.Driver
    username: inditex
    password: xetidni
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
springdoc:
  api-docs:
    path: /api-docs
  override-with-generic-response: false
